name: deploy-app
on:
  workflow_dispatch: 

jobs:
    deploy:
      env:
        DOCKERHUB_USER : ${{ vars.DOCKERHUB_USER}}
      runs-on: self-hostet
      steps:
        - name: checkout code
          run: action/checkout@v4

        - name: deloy with docker compose
          run: docker compose up -d  --build
  
