name: Deploye To Server

on: workflow_call


jobs:
   deploye:
     runs-on: ubuntu-latest
     steps:

        - name: Code checkOut
          uses: actions/checkout@v4
          
        - name: SSH to  Server
          uses: appleboy/ssh-action@v1.0.3
          with:
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.EC2_USERNAME }}
            key: ${{ secrets.SSH_PRIVATE_KEY}}
            script: |
               mkdir -p /home/ubuntu/python-flask-app
               cd /home/ubuntu/python-flask-app     # path to your app on server
               docker image prune -f
               docker stop python-flask-app || true
               docker rm python-flask-app || true
               #docker pull cusit/python-flask-app:${{github.sha}}
              #docker run -d -p 5000:5000 --name python-flask-app cusit/python-flask-app:${{github.sha}}               
              # #Docker-compose up -d --build  
      
          
           
            
            
            #script: |
             # echo "Starting Deployement"
              #mkdir devops121212
            
