name: deploy-app
on:
  workflow_dispatch: 

jobs:
    deploy:
      env:
        DOCKERHUB_USER : ${{vars.DOCKER_USERNAME}}
        DOCKER_TAG: ${{github.sha}}
      runs-on: self-hosted
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        
        - name: deloy with docker compose
          run: docker compose up -d  --build
  
