name: Deploye To Server

on: workflow_call


jobs:
   deploye:
     runs-on: ubuntu-latest
     steps:

        - name: Code checkOut
          uses: actions/checkout@v4
          
        - name: SSH to  Server
          uses: appleboy/ssh-action@v1.0.3
          with:
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.EC2_USERNAME }}
            key: ${{ secrets.SSH_PRIVATE_KEY}}
            script: |
               cd /home/ubuntu/python-flask-app      # path to your app on server
               docker-compose pull                  # pull latest images
               docker-compose up -d --build         # build & run containers in background
               docker ps    
          
           
            
            
            #script: |
             # echo "Starting Deployement"
              #mkdir devops121212
            
