
name: DevSecOpsPipline

on:
  push:
    branches: [main]

jobs:
    code-quality:
     uses: ./.github/workflows/code-quality.yml
    secretes-scan:
     uses: ./.github/workflows/secretes-scan.yml
    dependencies-scane:
     uses: ./.github/workflows/dependencies-scane.yml
    docker-lint:
     uses: ./.github/workflows/docker-lint.yml
    Docker-Build-Push:
     needs: [code-quality,secretes-scan,dependencies-scane,docker-lint]
     uses: ./.github/workflows/docker-work-flows.yml
        
