name: python-matrix

on:
  push:
     branches: [main]

jobs:
  validation:
      runs-on: ubuntu-latest

      steps:
          - name: code checkOut 
            uses: actions/checkout@v4

          - name: setup python3.13
            uses: actions/setup-python@v4
            with:
              python-version: "3.13"

          - name: install dependecies
            run: pip install -r requirements.txt

          - name: run linter
            run: flake8 app.py
