name: Secrets Scane

on: 
    workflow_call:
    
jobs:

    secrets-scane:
        runs-on: ubuntu-latest
        steps: 

            - name: Checkout Code
              uses: actions/checkoutcode@v4
              with:
                fetch-depth: 0


            - name: Run GitLeak Scanner
              uses: gitleaks/gitleaks-action@v2
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

               


